#!/usr/bin/env bash
# =============================================================================
# very-princess — Soroban Contract Deploy Script
# =============================================================================
# This script builds the PayoutRegistry contract and deploys it to the Stellar
# Testnet. After a successful deployment, the CONTRACT_ID is written to the
# root .env.contracts file so that the backend and frontend can read it.
#
# Prerequisites:
#   - Rust + wasm32 target:  rustup target add wasm32-unknown-unknown
#   - Stellar CLI (>=21):    cargo install stellar-cli --locked --features opt
#   - Funded Testnet account: https://developers.stellar.org/network/testnet/get-started
#
# Usage:
#   export DEPLOYER_SECRET="S..."   # Your Testnet secret key
#   chmod +x scripts/deploy.sh
#   ./scripts/deploy.sh
# =============================================================================

set -euo pipefail

# ── Colour helpers ──────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Colour

log()  { echo -e "${CYAN}[deploy]${NC} $*"; }
ok()   { echo -e "${GREEN}[deploy]${NC} ✓ $*"; }
warn() { echo -e "${YELLOW}[deploy]${NC} ⚠ $*"; }
err()  { echo -e "${RED}[deploy]${NC} ✗ $*" >&2; exit 1; }

# ── Configuration ───────────────────────────────────────────────────────────

# Resolve the repo root regardless of where this script is called from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTRACTS_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${CONTRACTS_DIR}/../.." && pwd)"

# Output artefacts.
WASM_PATH="${CONTRACTS_DIR}/target/wasm32-unknown-unknown/release/very_princess_contracts.wasm"
ENV_CONTRACTS_FILE="${REPO_ROOT}/.env.contracts"

# Stellar Testnet defaults — override via environment variables if needed.
NETWORK="${NETWORK:-testnet}"
RPC_URL="${RPC_URL:-https://soroban-testnet.stellar.org}"
NETWORK_PASSPHRASE="${NETWORK_PASSPHRASE:-Test SDF Network ; September 2015}"

# ── Validate Prerequisites ──────────────────────────────────────────────────

log "Validating prerequisites..."

if ! command -v stellar &>/dev/null; then
  err "Stellar CLI not found. Install: cargo install stellar-cli --locked --features opt"
fi

if [[ -z "${DEPLOYER_SECRET:-}" ]]; then
  err "DEPLOYER_SECRET is not set. Export your funded Testnet secret key and retry."
fi

ok "Prerequisites satisfied."

# ── Step 1: Build the contract ──────────────────────────────────────────────

log "Building PayoutRegistry contract (optimised WASM)..."

(
  cd "${CONTRACTS_DIR}"
  stellar contract build --profile release
)

if [[ ! -f "${WASM_PATH}" ]]; then
  err "WASM build artefact not found at: ${WASM_PATH}"
fi

WASM_SIZE=$(stat -c%s "${WASM_PATH}" 2>/dev/null || stat -f%z "${WASM_PATH}")
ok "Contract built — ${WASM_SIZE} bytes at ${WASM_PATH}"

# ── Step 2: Configure Stellar CLI network ──────────────────────────────────

log "Configuring Stellar CLI for network: ${NETWORK} (${RPC_URL})"

stellar network add "${NETWORK}" \
  --rpc-url "${RPC_URL}" \
  --network-passphrase "${NETWORK_PASSPHRASE}" \
  2>/dev/null || warn "Network '${NETWORK}' already configured — continuing."

# ── Step 3: Import deployer identity ───────────────────────────────────────

IDENTITY_NAME="very-princess-deployer"
log "Importing deployer keypair as identity '${IDENTITY_NAME}'..."

stellar keys add "${IDENTITY_NAME}" \
  --secret-key "${DEPLOYER_SECRET}" \
  2>/dev/null || warn "Identity '${IDENTITY_NAME}' already exists — overwriting."

stellar keys add "${IDENTITY_NAME}" --secret-key "${DEPLOYER_SECRET}" 2>/dev/null || true

DEPLOYER_ADDRESS=$(stellar keys address "${IDENTITY_NAME}")
log "Deployer address: ${DEPLOYER_ADDRESS}"

# ── Step 4: Deploy to Testnet ───────────────────────────────────────────────

log "Deploying PayoutRegistry to Stellar ${NETWORK}..."

CONTRACT_ID=$(stellar contract deploy \
  --wasm "${WASM_PATH}" \
  --source "${IDENTITY_NAME}" \
  --network "${NETWORK}")

if [[ -z "${CONTRACT_ID}" ]]; then
  err "Deployment failed — no contract ID returned."
fi

ok "Contract deployed! CONTRACT_ID=${CONTRACT_ID}"

# ── Step 5: Persist contract ID ─────────────────────────────────────────────

log "Writing CONTRACT_ID to ${ENV_CONTRACTS_FILE}..."

# Write (or overwrite) the file — this is read by backend and frontend at startup.
cat > "${ENV_CONTRACTS_FILE}" <<EOF
# Auto-generated by packages/contracts/scripts/deploy.sh
# DO NOT edit manually — re-run deploy.sh to update.
# Network: ${NETWORK} | Deployed: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
CONTRACT_ID=${CONTRACT_ID}
DEPLOYER_ADDRESS=${DEPLOYER_ADDRESS}
EOF

ok "Saved to ${ENV_CONTRACTS_FILE}"

# ── Done ────────────────────────────────────────────────────────────────────

echo ""
echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Deployment complete!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Contract ID   : ${CYAN}${CONTRACT_ID}${NC}"
echo -e "  Network       : ${CYAN}${NETWORK}${NC}"
echo -e "  Deployer      : ${CYAN}${DEPLOYER_ADDRESS}${NC}"
echo -e "  Stellar Expert : ${CYAN}https://testnet.stellar.expert/explorer/testnet/contract/${CONTRACT_ID}${NC}"
echo ""
echo "  Next steps:"
echo "    1. Copy .env.example → .env and set CONTRACT_ID=${CONTRACT_ID}"
echo "    2. Run: npm run dev"
echo ""
